-- The 12 cold cases came from the design prototype (realufo-handoff/data.js).
-- Their pull quotes and citations couldn't be traced to sources, the status
-- lines were unsourced claims of official status, five cases were labelled
-- "AARO Archive" though no such AARO file exists, and several intro texts had
-- errors (wrong aircraft, wrong sheriff's office, AARO report claims, invented
-- figures). Keep only what holds up; the Roswell press-release quote is real.
UPDATE cases SET pull=NULL, pull_cite=NULL, status=NULL;
UPDATE cases SET archive=NULL WHERE archive NOT IN (SELECT id FROM archives) OR slug IN ('jal-1628','tehran','travis-walton','ohare-2006','stephenville');
UPDATE cases SET pull='The many rumors regarding the flying disc became a reality yesterday when the intelligence office of the 509th Bomb group of the Eighth Air Force, Roswell Army Air Field, was fortunate enough to gain possession of a disc through the cooperation of one of the local ranchers and the sheriff''s office of Chaves County.', pull_cite='— Roswell Army Air Field press release (Lt. Walter Haut), 8 July 1947' WHERE slug='roswell';
UPDATE cases SET archive_label='FAA records' WHERE slug='jal-1628';
UPDATE cases SET archive_label='DIA report · FOIA' WHERE slug='tehran';
UPDATE cases SET archive_label=NULL WHERE slug='travis-walton';
UPDATE cases SET archive_label='FAA · Chicago Tribune' WHERE slug='ohare-2006';
UPDATE cases SET archive_label='FAA radar · MUFON FOIA' WHERE slug='stephenville';
UPDATE cases SET lede='On 21 December 1978, a Safe Air Argosy freighter on a night cargo run reported multiple unidentified luminous objects pacing the aircraft over Cook Strait and the Kaikoura coast. Wellington Air Traffic Control logged simultaneous unknown radar returns. On 30–31 December an Australian TV news crew, led by reporter Quentin Fogarty, boarded a second Argosy flight to investigate and captured 16 mm motion-picture film of bright objects. The Royal New Zealand Air Force investigated; the New Zealand Defence Force released its UFO files to the public in December 2010.' WHERE slug='kaikoura';
UPDATE cases SET lede='On the night of 17 November 1986, Japan Air Lines cargo flight JL1628, a Boeing 747 freighter en route from Reykjavík to Anchorage, reported being paced for about 50 minutes by unidentified lights over interior Alaska. Captain Kenju Terauchi reported two smaller objects ahead of the aircraft, followed by a far larger object he described as "twice the size of an aircraft carrier". The FAA''s Anchorage Air Route Traffic Control Center reviewed its radar data; the FAA''s case documents, including the crew interviews and radar data, were released in March 1987.' WHERE slug='jal-1628';
UPDATE cases SET lede='On the night of 19 September 1976, the Imperial Iranian Air Force scrambled two F-4 Phantoms from Shahrokhi Air Base to investigate a brilliant object reported by civilians over Tehran. Both interceptor crews, the second flown by Lt. Parviz Jafari, reported that as they closed on the object their weapons systems and communications failed. The events were summarised in a U.S. Defense Intelligence Agency report dated 22 September 1976, later released under the Freedom of Information Act.' WHERE slug='tehran';
UPDATE cases SET lede='On the afternoon of 24 April 1964, Socorro Police Officer Lonnie Zamora broke off pursuit of a speeding vehicle south of the city when he saw a flash of flame and heard a roar in an arroyo to his west. Driving toward it, Zamora saw what he first took to be an overturned car, then described as a smooth, egg-shaped object on legs, with two figures in "white coveralls" beside it. The object lifted off with a loud roar and departed, leaving four depressions in the ground and a charred bush. Project Blue Book investigated; the file is held at NARA in Record Group 341, and the case remained classified "Unidentified" when Blue Book closed in 1969.' WHERE slug='socorro';
UPDATE cases SET lede='On the evening of 5 November 1975, a seven-man forestry thinning crew led by Mike Rogers was driving home from a contract job in the Apache-Sitgreaves National Forest when they saw a luminous object hovering over a clearing. Crew member Travis Walton, 22, left the truck to look; the others said he was struck by a beam of light from the object and collapsed. The six remaining crew members drove off and reported the events to the Navajo County Sheriff''s Office that night. Walton was missing for five days; the sheriff''s office searched for him and initially investigated the crew for possible homicide. Walton reappeared in Heber on 10 November 1975. Five of the six co-workers passed a polygraph examination administered by Cy Gilson of the Arizona Department of Public Safety.' WHERE slug='travis-walton';
UPDATE cases SET lede='On the evening of 4 October 1967, at about 23:20 ADT, multiple civilian witnesses at Shag Harbour, Nova Scotia reported a row of lights descending at a shallow angle and striking the Atlantic Ocean offshore. Royal Canadian Mounted Police officers from the Barrington Passage detachment went to the shore and saw a light and a patch of yellowish foam on the water. The RCMP, the Canadian Coast Guard and navy divers from HMCS Granby searched the area over the following days and found nothing. The case file is held at Library and Archives Canada.' WHERE slug='shag-harbour';
UPDATE cases SET lede='On the afternoon of 7 November 2006, at about 16:15 local time, United Airlines employees reported seeing a dark, disc-shaped object hovering over Gate C-17 at Chicago O''Hare International Airport. Witnesses said it hovered for several minutes before shooting straight up through the low cloud deck, leaving a hole in the clouds. The Federal Aviation Administration initially said it had no record of reports; after a Chicago Tribune investigation by reporter Jon Hilkevitch, the FAA acknowledged the sighting and attributed it to a weather phenomenon.' WHERE slug='ohare-2006';
UPDATE cases SET lede='On the evening of 8 January 2008, dozens of witnesses around Stephenville in Erath County, Texas, reported a large formation of lights moving silently at low altitude. Witnesses included Erath County constable Lee Roy Gaitan, local pilot Steve Allen and businessman Ricky Sorrells. A FOIA request by the Mutual UFO Network (MUFON) obtained FAA radar data showing unidentified returns in the area at the reported time. The U.S. Air Force first said no military aircraft were in the area, then revised its statement on 23 January 2008 to say that ten F-16s from the 457th Fighter Squadron at Naval Air Station Fort Worth Joint Reserve Base had been training there that evening.' WHERE slug='stephenville';
UPDATE cases SET lede='On the afternoon of 8 January 1981, retired mason Renato Nicolaï reported that an object he described as two saucers joined rim to rim, lead-coloured, landed in his garden in the Provençal village of Trans-en-Provence. He said it stayed on the ground briefly, then rose and departed with a faint whistle, leaving a circular ground mark. The local gendarmerie collected soil and plant samples the next day, and GEPAN, the UAP unit of the French space agency CNES (renamed GEIPAN in 2005), opened case 81/01 and analysed the samples.' WHERE slug='trans-en-provence';
UPDATE cases SET lede='On the night of 11 November 1979, TAE flight JK297, a Super Caravelle flying from Salzburg to the Canary Islands, diverted and made an unscheduled landing at Manises airport (Valencia) after the crew reported intense red lights approaching the aircraft at close range. Spanish air defence radar was alerted and a Mirage F1 fighter was scrambled from Los Llanos Air Base. The Spanish Air Force''s file on the case was declassified in 1994.' WHERE slug='manises';
UPDATE cases SET lede='On 20 May 1967, Stefan Michalak, an industrial mechanic from Winnipeg, was prospecting near Falcon Lake, Manitoba when he reported seeing two glowing objects, one of which landed on a rock nearby. He said he approached the landed object and touched it; as it lifted off, a blast of hot exhaust from a grid of vents burned his shirt and left a grid-pattern burn on his chest. Michalak returned to Winnipeg and was treated at Misericordia Hospital. The RCMP, the Royal Canadian Air Force and the Department of National Defence investigated; the case file is held at Library and Archives Canada.' WHERE slug='falcon-lake';
