-- Case stories fact-check (spec 2026-10-03-realufo-case-stories-design): the other
-- 10 case ledes rewritten to match the primary documents the stories cite
-- (worker/lib/caseStoryText.ts). Corrections include: Roswell retraction was the
-- next day and the Haut wording is unverified; Walton reappeared 11 Nov; O'Hare
-- ~4:30 p.m.; Falcon Lake burns on the upper abdomen; Tehran pilots unnamed and only
-- the second F-4 lost weapons; Manises flight was Palma-Tenerife; Trans-en-Provence
-- witness unnamed in the GEPAN note; Shag Harbour witnesses include the RCMP corporal.
UPDATE cases SET lede = 'On 8 July 1947 the public information office at Roswell Army Air Field, New Mexico, announced that personnel of the 509th Bomb Group had recovered a "flying disc" from a ranch near Roswell. The following day the press reported Brig. Gen. Roger Ramey, commanding the Eighth Air Force at Fort Worth, as saying the material was a weather balloon. The case drew little attention until 1978–80, when researchers began interviewing surviving witnesses. The Air Force reviewed it in 1994, concluding the debris most likely came from the balloon project Mogul, and again in 1997; the GAO''s 1995 records search found only two government records that originated in 1947.' WHERE slug = 'roswell';
UPDATE cases SET lede = 'On the evening of 17 November 1986, Japan Air Lines cargo flight JL1628, a Boeing 747 crossing Alaska from Reykjavík toward Anchorage, reported unknown traffic accompanying it. Captain Kenju Terauchi described lights and two objects ahead of the aircraft and later a much larger silhouette; in a January 1987 FAA interview he agreed with the inspector''s summary that it was about twice the size of an aircraft carrier. Military radar reported intermittent returns, but the FAA said its own radar data did not confirm the traffic and attributed a second target to a split return from the 747. The FAA released its case documents in March 1987.' WHERE slug = 'jal-1628';
UPDATE cases SET lede = 'Early on 19 September 1976, after residents of Tehran reported a bright object in the sky, the Imperial Iranian Air Force sent up two F-4 Phantoms. According to the U.S. Defense Attaché Office''s report, the first lost its instruments and communications as it closed on the object; the second, after a radar lock, lost communications and its weapons control panel as the pilot tried to fire a missile. The attaché report, dated 22 September and sent to the Defense Intelligence Agency the next day, names neither pilot.' WHERE slug = 'tehran';
UPDATE cases SET lede = 'On the evening of 5 November 1975, a seven-man forestry crew led by Mike Rogers was leaving a thinning job in the Apache-Sitgreaves National Forest near Heber, Arizona, when, they said, they saw a glowing object hovering above a clearing. Crew member Travis Walton, 22, walked toward it; the others said a beam of light threw him back, and they drove off. They reported him missing to the Navajo County Sheriff''s Office that night, and he was searched for until he telephoned from a Heber phone booth shortly after midnight on 11 November. A state polygraph examiner, testing the crew mainly to rule out foul play, judged five of the six truthful; polygraph tests of Walton himself later gave conflicting results.' WHERE slug = 'travis-walton';
UPDATE cases SET lede = 'On the afternoon of 7 November 2006, at about 4:30 p.m., United Airlines employees reported a dark, disc-shaped object hovering low over Gate C17 at Chicago O''Hare International Airport; they said it then shot up through the cloud deck, leaving a hole. The sighting became public on 1 January 2007 in a Chicago Tribune report by Jon Hilkevitch. The FAA, which first said it had no information, found a call about it on its tower tapes, said no controller saw the object and radar showed nothing unusual, and attributed it to a weather phenomenon without investigating further.' WHERE slug = 'ohare-2006';
UPDATE cases SET lede = 'On the evening of 8 January 2008, residents around Stephenville and Dublin in Erath County, Texas, reported a large, silent object with bright lights flying low and fast. Witnesses quoted by the Associated Press included Erath County Constable Lee Roy Gaitan and pilot Steve Allen. The Air Force Reserve first said none of its aircraft were in the area, then said on 23 January that ten F-16s from the 457th Fighter Squadron had been training nearby that evening. A study of FAA radar data obtained under the Freedom of Information Act by researchers with the Mutual UFO Network (MUFON) reported unidentified returns, an interpretation no government body has confirmed.' WHERE slug = 'stephenville';
UPDATE cases SET lede = 'Late on the evening of 4 October 1967, an RCMP corporal from the Barrington Passage detachment and six other witnesses reported a dark object with four white lights descending rapidly into the sea off Lower Woods Harbour, near Shag Harbour, Nova Scotia, with a whistling sound and a bright flash. A single light floated on the water and sank before a boat could reach it. A Coast Guard lifeboat, local boats and, from 6 to 8 October, Canadian Forces divers searched the area and found nothing. The National Defence file, held at Library and Archives Canada, records no findings.' WHERE slug = 'shag-harbour';
UPDATE cases SET lede = 'On 20 May 1967, Stefan Michalak, an industrial mechanic from Winnipeg, reported that while prospecting near Falcon Lake, Manitoba, he saw two saucer-shaped objects on the ground, watched one leave, and approached the other; when he touched it, he said, it began to rotate and a blast from its exhaust burned his shirt and his upper abdomen. He was treated at Misericordia Hospital in Winnipeg. The RCMP, the Royal Canadian Air Force and federal radiation specialists investigated, and later found a small radium-contaminated spot at the site whose origin they could not determine. The file is held at Library and Archives Canada.' WHERE slug = 'falcon-lake';
UPDATE cases SET lede = 'On the afternoon of 8 January 1981, a man working on his terrace in Trans-en-Provence, in the Var, reported that a lead-coloured craft shaped like two inverted plates landed briefly below him with a slight whistle, then rose and left, leaving a circular mark on the ground. Gendarmes took soil and plant samples the next day. GEPAN, the UAP unit of the French space agency CNES (now GEIPAN), studied the case in its Technical Note no. 16, and GEIPAN classifies it as unidentified.' WHERE slug = 'trans-en-provence';
UPDATE cases SET lede = 'On the night of 11 November 1979, the crew of TAE flight JK 297, flying from Palma to Tenerife, reported two intense red lights near their aircraft south of Ibiza and diverted to land at Manises airport, Valencia. Airport staff saw bright lights in the sky, and a fighter scrambled from Albacete air base made no radar contact. The Spanish Air Force file on the incident, numbered 791111, was declassified in 1994.' WHERE slug = 'manises';
