-- Case stories batch 2 (spec 2026-10-03-realufo-case-stories-batch2-design):
-- 20 new cold cases whose fact-checked stories live in worker/lib/caseStoryText2.ts.
-- Ledes are written from the owner-approved stories; every fact in them is cited there.
-- pull/pull_cite stay NULL (the stories' section quotes carry the quotes).
INSERT INTO cases(slug,name,archive,archive_label,accent,coord,lede,pull,pull_cite,status) VALUES
('belgian-wave','Belgian wave 1989–90',NULL,'Belgian Air Force · U.S. DoD','#fdda24','◉ 50.6333° N · 4.9167° E · Ramillies, Belgium · 30–31 Mar 1990','On the night of 30–31 March 1990 two Belgian F-16s were scrambled after gendarmes and two ground radars reported lights south-east of Brussels; the pilots locked on three times for a few seconds but never saw anything. The Air Force''s report could not identify the source, and a physicist later traced the extreme speeds to the radar itself.',NULL,NULL,NULL),
('cash-landrum','Cash-Landrum 1980',NULL,'USAF FOIA · Cash v. United States','#4a9eff','◉ 30.1410° N · 95.1110° W · FM 1485 near Huffman, Texas · 29 Dec 1980','On 29 December 1980 Betty Cash, Vickie Landrum and seven-year-old Colby Landrum reported a glowing, flaming object and a swarm of twin-rotor helicopters on FM 1485 in Texas, and later blamed burns and illness on it. Army and Air Force officials swore no such craft was theirs, and the three witnesses'' $20 million lawsuit was dismissed in October 1986.',NULL,NULL,NULL),
('coyne','Coyne helicopter 1973',NULL,'U.S. Army · CUFOS','#4a9eff','◉ 40.7638° N · 82.3740° W · Route 430 bridge, Charles Mill Reservoir, near Mansfield, Ohio · 18 Oct 1973','On 18 October 1973 an Army Reserve helicopter crew near Mansfield, Ohio, reported a near midair collision with an unidentified flying object, followed by a climb to 3,500 feet with the collective fully down. The Army''s own report came five weeks later, and the case is absent from AARO''s 2024 historical report.',NULL,NULL,NULL),
('gimbal','Gimbal 2015',NULL,'AARO Archive','#4a9eff','◉ 36.8203° N · 76.0331° W · Off U.S. East Coast (VFA-11 base, NAS Oceana, Va.) · Jan 2015','A 34-second Navy F/A-18 infrared video from January 2015, leaked in 2017 and officially released by the Pentagon in 2020, shows a glowing object whose outline turns on screen. AARO still lists it as an unresolved case.',NULL,NULL,NULL),
('phoenix-lights','Phoenix Lights 1997',NULL,'AP · Phoenix New Times','#4a9eff','◉ 33.4484° N · 112.0740° W · Phoenix, Arizona · 13 Mar 1997','On the night of 13 March 1997 a V of five lights crossed Arizona around 8:30 p.m., and a row of hovering lights appeared southwest of Phoenix at about 10 p.m. The Maryland Air National Guard later said its A-10s had dropped flares that night; who flew the earlier formation was never established.',NULL,NULL,NULL),
('tic-tac','Nimitz "Tic Tac" 2004',NULL,'AARO Archive','#4a9eff','◉ 31.3333° N · 117.1667° W · Off Baja California · 14 Nov 2004','On 14 November 2004, F/A-18F crews from USS Nimitz sent to a radar contact off Baja California saw a white, wingless "Tic Tac" shaped object, and a second jet recorded it on its targeting pod. The Department of Defense released the video in 2020 and says the phenomena remain "unidentified."',NULL,NULL,NULL),
('operacao-prato','Operação Prato 1977',NULL,'Brazil · Arquivo Nacional','#009c3b','◉ 0.9369° S · 48.2819° W · Colares, Pará · Oct–Nov 1977','In late 1977 an Air Force intelligence team camped in Colares, Pará, where villagers said beams of light from the sky were attacking them. Its reports record sightings, symptoms and blurred photos, while an I COMAR officer told the press it was all an optical illusion.',NULL,NULL,NULL),
('trindade','Trindade Island 1958',NULL,'Project Blue Book · Brazilian Navy','#009c3b','◉ 20.5000° S · 29.3000° W · Trindade Island, Brazil · 16 Jan 1958','On 16 January 1958, photographs of an alleged flying saucer were taken from the Brazilian Navy ship Almirante Saldanha off Trindade Island. The Navy Ministry said the photographs were not sufficient proof, and U.S. naval intelligence and Project Blue Book filed them as a hoax.',NULL,NULL,NULL),
('varginha','Varginha 1996',NULL,'Brazil · Superior Tribunal Militar','#009c3b','◉ 21.5685° S · 45.4363° W · Jardim Andere, Varginha, Minas Gerais · 20 Jan 1996','On 20 January 1996 three young women in Varginha, Minas Gerais, said they saw a crouching creature in a vacant lot, and ufologists later accused the Army of capturing it. The Army''s own 357-page inquiry, now public at the Superior Military Court, concluded that the girls probably saw a local man known as "Mudinho" and called the ufologists'' book fiction.',NULL,NULL,NULL),
('el-bosque','El Bosque 2010',NULL,'Chile · CEFAA','#d52b1e','◉ 33.5660° S · 70.6820° W · El Bosque Air Base, Santiago · 5 Nov 2010','At a Chilean Air Force ceremony at El Bosque on 5 November 2010, nobody saw anything unusual, but two video cameras caught a small oval object among the aircraft. CEFAA called it unexplained, two analysts disagreed over whether it was an insect, and the committee left the case unsolved.',NULL,NULL,NULL),
('valensole','Valensole 1965',NULL,'France · GEIPAN','#0055a4','◉ 43.8432° N · 5.9688° E · L''Olivol, Valensole · 1 Jul 1965','At dawn on 1 July 1965 a lavender farmer near Valensole, later named as Maurice Masse, reported a machine the size of a small car in his field. The gendarmerie heard of it by rumour the next evening, measured a hole and a cross of furrows, and six weeks later took a fuller account of two small beings and fifteen minutes of immobility.',NULL,NULL,NULL),
('chiles-whitted','Chiles–Whitted 1948','nara','NARA Archive','#cbd5e1','◉ 32.1742° N · 86.5497° W · 20 mi SW of Montgomery, Alabama · 24 Jul 1948','In the early hours of 24 July 1948 two Eastern Air Lines pilots reported a wingless object trailing flame, with two rows of lit windows, passing their DC-3 near Montgomery, Alabama. The Air Force file holds their statements, an astronomer''s meteor hypothesis and a final evaluation of probable meteor.',NULL,NULL,NULL),
('condon-committee','Condon Committee 1966',NULL,'War.gov · Condon Report','#4a9eff','◉ 40.0076° N · 105.2659° W · University of Colorado, Boulder · 1966–1968','In 1966 the U.S. Air Force chose the University of Colorado for an outside scientific study of UFO reports, after its own advisers called the problem "99% public relations". Edward Condon concluded that further extensive study probably could not be justified, and the Air Force cited the report when it closed Project Blue Book in 1969.',NULL,NULL,NULL),
('levelland','Levelland 1957','nara','NARA Archive','#cbd5e1','◉ 33.5873° N · 102.3780° W · Levelland, Texas · 2–3 Nov 1957','On the night of 2–3 November 1957, drivers near Levelland, Texas, reported a glowing object that stalled their engines and put out their lights. Project Blue Book recorded six observers and closed the case as ball lightning, a verdict physicist James McDonald told Congress in 1968 could not stand.',NULL,NULL,NULL),
('lubbock-lights','Lubbock Lights 1951','nara','NARA Archive','#cbd5e1','◉ 33.5779° N · 101.8552° W · Lubbock, Texas · 25 Aug 1951','From 25 August 1951, Texas Tech professors in Lubbock watched formations of faint lights cross the night sky, and on 30 August freshman Carl Hart Jr. photographed formations of 18 or 20 of them. Air Force investigators could neither prove his photographs fake nor identify what the professors saw.',NULL,NULL,NULL),
('mantell','Mantell 1948','nara','NARA Archive','#cbd5e1','◉ 37.9069° N · 85.9719° W · Godman Field · Fort Knox, KY · 7 Jan 1948','On 7 January 1948 Capt. Thomas F. Mantell, Jr., leading a flight of National Guard P-51s, climbed after a bright object hanging south of Godman Field, Kentucky, and died in a crash at Franklin. The case files record his last radio call in different ways, and the Air Force''s explanation moved from Venus to a balloon that no one could trace.',NULL,NULL,NULL),
('mcminnville','McMinnville 1950',NULL,'Condon Report · DTIC','#4a9eff','◉ 45.1042° N · 123.3306° W · Trent farm, near McMinnville, Oregon · 11 May 1950','On 11 May 1950 Paul Trent took two photographs of a disk-shaped object over his farm near McMinnville, Oregon. The Air Force-funded Condon study found them consistent with what the witnesses described, but said it could not rule out a model hanging from an overhead wire.',NULL,NULL,NULL),
('robertson-panel','Robertson Panel 1953','nara','NARA Archive','#cbd5e1','◉ 38.9072° N · 77.0369° W · Washington, D.C. · 14–17 Jan 1953','In January 1953 five scientists convened by the CIA reviewed the government''s UFO evidence and found no indication of a direct physical threat to national security. Their two-page report urged that UFOs be stripped of their special status; the word "debunking" appears only in the unofficial minutes.',NULL,NULL,NULL),
('cosford','Cosford 1993',NULL,'UK · The National Archives','#c8102e','◉ 52.6405° N · 2.3053° W · RAF Cosford, Shropshire · 31 Mar 1993','In the early hours of 31 March 1993, police and military witnesses across Britain, including an RAF police patrol at Cosford, reported bright lights in the sky. An MoD desk officer argued an unidentified object had evaded UK air defences; The National Archives later concluded most sightings were a Russian rocket re-entering the atmosphere.',NULL,NULL,NULL),
('rendlesham','Rendlesham Forest 1980',NULL,'UK · The National Archives','#c8102e','◉ 52.0889° N · 1.4492° E · Rendlesham Forest, near RAF Woodbridge, Suffolk · 27–29 Dec 1980','In December 1980 USAF security patrolmen reported a glowing object in Rendlesham Forest outside RAF Woodbridge, and Deputy Base Commander Lt Col Charles Halt set down their account, and lights he saw himself, in a memo of 13 January 1981. The Ministry of Defence queried the radiation readings, then concluded the sightings were of no defence significance.',NULL,NULL,NULL);
