-- 0042 Short motion scores: how much the FIRST FEW FRAMES of each 9:16
-- Short move (mean inter-frame abs difference of the first ~2 s, 0-255 scale).
-- The feed's "Short clips" carousel autoplays each card muted + looping while
-- on screen, so clips that open on a static title card look dead: the feed
-- orders clips by motion DESC (see worker/routes/shorts.ts `orderMotion`).
--
-- Scored by scripts/short_motion.py:
--   * backfill: every live Short's served file (showcase file if the record
--     has one, else the clips-v/ twin) — the INSERTs below;
--   * ongoing: crawler/ingest/clips.py scores each rendered twin at render
--     time; scripts/publish.sh --showcase scores the hand-made file at upload.
-- Re-run the backfill any time cuts are re-rendered (INSERT ... ON CONFLICT
-- DO UPDATE is idempotent).
CREATE TABLE IF NOT EXISTS short_motion (
  record_id TEXT NOT NULL,
  kind TEXT NOT NULL CHECK (kind IN ('showcase', 'twin')),
  motion REAL NOT NULL,
  frames INTEGER NOT NULL DEFAULT 0,
  computed_at INTEGER NOT NULL,
  PRIMARY KEY (record_id, kind)
);
CREATE INDEX IF NOT EXISTS idx_short_motion_motion ON short_motion (motion DESC);

-- Backfill (computed 2026-10-06, scripts/short_motion.py --backfill):
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('CONGRESS-CHRG-119hhrg61718', 'showcase', 0.02, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('65-hs1-834228961-62-hq-83894-section-8', 'showcase', 0.2, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('FBI-UAP-PR003', 'showcase', 0.17, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('CIA-UAP-003', 'showcase', 0.01, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOE-UAP-D004', 'showcase', 0.17, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-D138', 'showcase', 0.0, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR121', 'showcase', 2.67, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR067', 'showcase', 16.04, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR104', 'showcase', 1.94, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR028', 'showcase', 1.92, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('AARO-956955', 'showcase', 0.0, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('LLE-UAP-PR004', 'twin', 0.08, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('LLE-UAP-PR003', 'twin', 2.85, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('LLE-UAP-PR002', 'twin', 0.33, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('LLE-UAP-PR001', 'twin', 0.61, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('FBI-UAP-PR007', 'twin', 3.03, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR159', 'twin', 2.78, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR152', 'twin', 2.62, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR151', 'twin', 9.21, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR150', 'twin', 0.38, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR149', 'twin', 2.15, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR148', 'twin', 6.85, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR144', 'twin', 2.44, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR143', 'twin', 5.53, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR142', 'twin', 0.19, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR141', 'twin', 1.56, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR140', 'twin', 2.8, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR136', 'twin', 7.39, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR135', 'twin', 0.85, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR134', 'twin', 4.39, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR133', 'twin', 1.75, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR127', 'twin', 2.28, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR126', 'twin', 4.48, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR125', 'twin', 2.16, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR124', 'twin', 2.35, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR123', 'twin', 1.53, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR122', 'twin', 1.13, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR120', 'twin', 2.4, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR119', 'twin', 3.94, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR118', 'twin', 1.53, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR117', 'twin', 3.61, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('AARO-DOD_111469070', 'twin', 2.27, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('AARO-DOD_111469069', 'twin', 0.64, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('AARO-DOD_111426410', 'twin', 0.37, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('AARO-DOD_111426407', 'twin', 1.64, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('AARO-DOD_111426396', 'twin', 1.65, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('AARO-DOD_111415223', 'twin', 0.19, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('AARO-DOD_111415215', 'twin', 0.35, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('AARO-DOD_111415209', 'twin', 2.61, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('AARO-DOD_111311872', 'twin', 11.32, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('AARO-DOD_111311867', 'twin', 0.74, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('AARO-DOD_111311861', 'twin', 0.41, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('AARO-DOD_111311856', 'twin', 11.74, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('AARO-DOD_111311850', 'twin', 39.77, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('AARO-DOD_111300649', 'twin', 8.64, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('AARO-DOD_111294469', 'twin', 35.7, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('AARO-DOD_111217027', 'twin', 0.54, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('AARO-DOD_111216951', 'twin', 0.39, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('AARO-DOD_111216897', 'twin', 3.04, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('AARO-DOD_111038535', 'twin', 17.08, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('AARO-DOD_110999231', 'twin', 0.03, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('AARO-DOD_110982722', 'twin', 30.63, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('AARO-DOD_110956846', 'twin', 5.04, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('AARO-DOD_110891172', 'twin', 2.2, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('AARO-DOD_110886776', 'twin', 3.62, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('AARO-DOD_110872545-1920x1080-9000k', 'twin', 1.08, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('AARO-DOD_110692805-1920x1080-9000k', 'twin', 8.69, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('AARO-DOD_110692791', 'twin', 0.45, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('AARO-DOD_109670991', 'twin', 1.6, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('AARO-DOD_109584445', 'twin', 2.04, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('AARO-DOD_109584439', 'twin', 0.11, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('AARO-DOD_109584436', 'twin', 0.15, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('WARGOV-VID-111689030', 'twin', 0.5, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('WARGOV-VID-111689022', 'twin', 1.26, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('WARGOV-VID-111689011', 'twin', 1.99, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('WARGOV-VID-111689005', 'twin', 0.0, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('WARGOV-VID-111688997', 'twin', 0.26, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('WARGOV-VID-111688970', 'twin', 0.12, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('WARGOV-VID-111688825', 'twin', 0.18, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('WARGOV-VID-111688816', 'twin', 0.42, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('WARGOV-VID-111688809', 'twin', 0.52, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('WARGOV-VID-111688775', 'twin', 4.86, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('WARGOV-VID-111688762', 'twin', 1.27, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('WARGOV-VID-111688723', 'twin', 7.42, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('FBI-UAP-PR006', 'twin', 3.48, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('FBI-UAP-PR005', 'twin', 0.0, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('FBI-UAP-PR004', 'twin', 1.13, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('FBI-UAP-PR002', 'twin', 0.55, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('FBI-UAP-PR001', 'twin', 0.32, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR116', 'twin', 0.58, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR115', 'twin', 2.58, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR114', 'twin', 0.34, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR113', 'twin', 0.48, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR112', 'twin', 3.51, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR111', 'twin', 0.71, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR110', 'twin', 0.43, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR109', 'twin', 7.72, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR108', 'twin', 2.09, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR107', 'twin', 0.58, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR106', 'twin', 5.68, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR105', 'twin', 5.3, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR103', 'twin', 0.15, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR102', 'twin', 1.08, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR101', 'twin', 6.07, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR100', 'twin', 2.19, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR099', 'twin', 0.62, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR098', 'twin', 1.62, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR097', 'twin', 1.32, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR096', 'twin', 4.78, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR095', 'twin', 3.07, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR094', 'twin', 0.3, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR093', 'twin', 1.59, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR092', 'twin', 0.28, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR091', 'twin', 0.42, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR090', 'twin', 0.89, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR089', 'twin', 1.39, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR088', 'twin', 15.98, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR087', 'twin', 17.81, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR086', 'twin', 3.5, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR085', 'twin', 1.18, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR084', 'twin', 4.9, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR083', 'twin', 1.71, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR082', 'twin', 0.45, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR081', 'twin', 3.46, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR080', 'twin', 1.94, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR079', 'twin', 0.46, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR078', 'twin', 1.52, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR077', 'twin', 2.66, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR076', 'twin', 20.57, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR075', 'twin', 7.46, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR074', 'twin', 0.65, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR073', 'twin', 0.09, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR072', 'twin', 0.0, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR071', 'twin', 1.31, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR070', 'twin', 1.7, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR069', 'twin', 4.56, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR068', 'twin', 0.32, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR066', 'twin', 7.82, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR065', 'twin', 0.26, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR064', 'twin', 0.43, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR063', 'twin', 0.85, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR062', 'twin', 17.48, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR061', 'twin', 1.6, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR060', 'twin', 8.28, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR059', 'twin', 1.72, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR058', 'twin', 19.24, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR057a', 'twin', 2.55, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR056', 'twin', 16.06, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR055', 'twin', 3.71, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR054', 'twin', 6.88, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR053', 'twin', 0.14, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR052', 'twin', 30.45, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR051', 'twin', 13.14, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR050', 'twin', 3.27, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR049', 'twin', 0.94, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR048', 'twin', 0.74, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR047', 'twin', 0.42, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR046', 'twin', 0.25, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR045', 'twin', 12.46, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR044', 'twin', 1.05, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR043', 'twin', 0.16, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR042', 'twin', 0.69, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR041', 'twin', 0.73, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR040', 'twin', 36.84, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR039', 'twin', 0.23, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR038', 'twin', 1.25, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR037', 'twin', 0.63, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR030', 'twin', 0.58, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR029', 'twin', 4.7, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
INSERT INTO short_motion (record_id, kind, motion, frames, computed_at) VALUES ('DOW-UAP-PR024', 'twin', 0.43, 16, 1791273909) ON CONFLICT(record_id, kind) DO UPDATE SET motion=excluded.motion, frames=excluded.frames, computed_at=excluded.computed_at;
