-- 0048_affiliate_shelf2.sql: second wave of Reading Shelf picks (12 -> 24).
-- Mirrors worker/lib/affiliate.ts PICKS entries 12-23 (sort order).
-- Apply manually in the D1 dashboard (git deploys do NOT run migrations);
-- verify with: SELECT count(*) FROM affiliate_picks;  -- expect 24

INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('The Report on Unidentified Flying Objects', 'Edward J. Ruppelt', 'The insider the shelf was missing: the Air Force captain who ran Project Blue Book 1951–1953 wrote the first serious account of the official investigation — Washington 1952, the Lubbock Lights, the Mantell crash.', 'Report on Unidentified Flying Objects Ruppelt', NULL, 'ruppelt,blue book,project grudge,project sign,washington 1952', 'project-blue-book', 12);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('Passport to Magonia', 'Jacques Vallée', 'Hynek''s own protégé goes furthest of all: UFO landings read against a thousand years of fairy lore. The multidimensional hypothesis starts here — the strangest book on the shelf, and the most influential.', 'Passport to Magonia Jacques Vallee', '0987422480', 'vallee,magonia,folklore,fairy', '', 13);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('UFOs: Generals, Pilots, and Government Officials Go on the Record', 'Leslie Kean', 'A New York Times bestseller by an investigative journalist: generals, pilots and officials — Tehran 1976, Belgium 1989, the Phoenix Lights — write their own chapters. The credibility cornerstone of the modern UAP era.', 'UFOs Generals Pilots Government Officials Go on the Record Leslie Kean', '0307717089', 'kean,generals,tehran,belgium,phoenix lights', 'congress', 14);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('Hunt for the Skinwalker', 'Colm Kelleher & George Knapp', 'Before the Pentagon''s $22 million program, there was the ranch: the NIDS science team''s instrumented investigation of Skinwalker Ranch — the direct predecessor of AAWSAP, by two of the same authors.', 'Hunt for the Skinwalker Kelleher Knapp', '1416505210', 'skinwalker,nids,bigelow,ranch', 'aawsap', 15);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('Crash at Corona', 'Stanton Friedman & Don Berliner', 'The nuclear physicist who reopened Roswell and an aviation writer rebuild the 1947 Corona crash from once-classified documents and debris-handler testimony. The definitive Roswell investigation.', 'Crash at Corona Friedman Berliner', '1605209392', 'roswell,corona,friedman,debris,retrieval', '', 16);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('Clear Intent', 'Lawrence Fawcett & Barry Greenwood', 'The FOIA pioneers'' book: hundreds of declassified pages prised out of the CIA, FBI and NSA in the 1970s–80s. The playbook for reading the very files in this archive.', 'Clear Intent Fawcett Greenwood', NULL, 'foia,fawcett,greenwood,citizens against ufo secrecy', '', 17);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('Encounter in Rendlesham Forest', 'Nick Pope, John Burroughs & Jim Penniston', 'Britain''s Roswell, on the record: the MoD''s former UFO-desk chief plus the two USAF airmen who walked into the forest in December 1980 — backed by formerly-classified documents.', 'Encounter in Rendlesham Forest Pope Burroughs Penniston', '1250038103', 'rendlesham,halt,bentwaters,woodbridge', '', 18);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('A.D. After Disclosure', 'Richard Dolan & Bryce Zabel', 'The historian behind the National Security State series teams with a Hollywood screenwriter to game out the day after disclosure — government, science, religion, markets. The ''what happens next'' book.', 'A.D. After Disclosure Dolan Zabel', '1601632223', 'disclosure,dolan,zabel', 'congress', 19);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('Witness to Roswell', 'Thomas Carey & Donald Schmitt', 'The Roswell deep-dive by its two most persistent investigators — new witnesses, the debris trail, and a foreword by Apollo astronaut Edgar Mitchell. The follow-on for Crash at Corona readers.', 'Witness to Roswell Carey Schmitt', '1637480032', 'roswell,carey,schmitt,marcel', '', 20);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('The Day After Roswell', 'Philip Corso & William Birnes', 'The wildest insider claim ever published: a Pentagon colonel says he seeded Roswell wreckage tech — integrated circuits, fiber optics, lasers — into American industry. A bestseller; read it skeptical.', 'The Day After Roswell Corso', '067101756X', 'corso,roswell,reverse engineering,day after roswell', '', 21);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('Abduction: Human Encounters with Aliens', 'John E. Mack', 'A Harvard psychiatrist and Pulitzer winner puts his career on the line for 60+ experiencers — the clinical counterweight to every ''it''s all bunk'' memo in this archive.', 'Abduction Human Encounters with Aliens John Mack', '1416575804', 'abduction,mack,experiencers,harvard', '', 22);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('Communion', 'Whitley Strieber', 'The 1987 bestseller that put the abduction experience on the map, by the horror novelist who lived it. Love it or doubt it — it''s the book every case file gets compared against.', 'Communion Whitley Strieber', '0061474185', 'communion,strieber,abduction', '', 23);
