-- 0049_affiliate_shelf3.sql: third wave of Reading Shelf picks (24 -> 36).
-- Mirrors worker/lib/affiliate.ts PICKS entries 24-35 (sort order).
-- NOTE: 0048 is taken twice (0048_affiliate_shelf2.sql + another session's
-- 0048_post_images.sql); this uses 0049 to avoid a third collision.
-- Apply via the d1-migrate workflow_dispatch (dashboard D1 console is behind
-- a human-verification check); verify with: SELECT count(*) FROM affiliate_picks;  -- expect 36

INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('Night Siege', 'J. Allen Hynek, Philip Imbrogno & Bob Pratt', '7,000+ sightings of silent boomerang craft over New York and Connecticut, 1982–86 — investigated by Hynek himself. The mass-sighting classic for the triangle files.', 'Night Siege Hudson Valley UFO Hynek Imbrogno', 'B0036DD2LC', 'hudson valley,triangle,boomerang,imbrogno', '', 24);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('The Interrupted Journey', 'John G. Fuller', 'September 1961, New Hampshire: the first abduction book, built from the Hills'' hypnosis transcripts — and they filed a contemporaneous Air Force report. Where the modern abduction story starts.', 'The Interrupted Journey John Fuller Betty Barney Hill', '0285624504', 'hill,betty,barney,abduction', '', 25);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('Fire in the Sky', 'Travis Walton', 'November 1975, Arizona: six loggers watch Walton taken, polygraphs all round, five days gone. The abduction case with the most witnesses — and a Hollywood film.', 'Fire in the Sky Travis Walton', '1569247102', 'walton,heber,snowflake,apache-sitgreaves', '', 26);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('Mirage Men', 'Mark Pilkington', 'The uncomfortable one: a journalist argues US intel promoted crashed-saucer stories — Bennewitz, Dulce, AFOSI''s Richard Doty — as cover for classified programs. Read it alongside the cover-up histories.', 'Mirage Men Mark Pilkington', '1845298578', 'disinformation,bennewitz,dulce,doty', '', 27);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('Area 51', 'Annie Jacobsen', 'The declassified history of Groom Lake — U-2, OXCART, Have Blue — plus the book''s notorious claim that Roswell was a Soviet hoax. Essential context, controversial ending.', 'Area 51 Annie Jacobsen', '0316202304', 'area 51,groom lake,roswell', '', 28);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('Phenomena', 'Annie Jacobsen', 'Forty years of CIA, DIA and Army remote-viewing and parapsychology — the Stargate Project, SRI, Puthoff and Targ — built entirely from declassified documents.', 'Phenomena Annie Jacobsen', '0316349364', 'remote viewing,stargate,psychic,esp', '', 29);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('American Cosmic', 'D. W. Pasulka', 'A religion professor''s field study of the modern UFO belief system — Silicon Valley contactee networks, the To the Stars milieu, Vallée and Garry Nolan as informants. The AATIP era, anthropologized.', 'American Cosmic D W Pasulka', '019069288X', 'aatip,uap,disclosure,to the stars', '', 30);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('Top Secret/Majic', 'Stanton T. Friedman', 'The physicist''s 21-year investigation of the MJ-12 documents — Truman''s alleged 1947 secret UFO group and the Roswell paper trail. The pro-MJ-12 case at its strongest.', 'Top Secret Majic Stanton Friedman', 'B0CH83SR9V', 'majestic 12,mj-12,roswell,truman', '', 31);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('The Majestic Documents', 'Robert M. Wood & Ryan S. Wood', 'The leaked documents themselves, compiled: the SOM1-01 recovery manual, the Interplanetary Phenomenon Unit report, the Einstein–Oppenheimer memo. Primary sources for the MJ-12 debate.', 'The Majestic Documents Wood', 'B002P26AJG', 'majestic 12,som1-01,interplanetary phenomenon unit,mj-12', '', 32);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('Dark Object', 'Don Ledger & Chris Styles', 'October 1967, Shag Harbour, Nova Scotia: three RCMP officers watch it go down, the Navy dives for it, the official file calls it a UFO. The world''s only government-documented UFO crash — Canada''s Roswell.', 'Dark Object Ledger Styles Shag Harbour', NULL, 'shag harbour,nova scotia,canada,1967', '', 33);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('Need to Know', 'Timothy Good', 'Good''s dossier of military-intelligence insider testimonies and declassified documents — carrier encounters, the Hillenkoetter quote, and how the services really handled UFOs.', 'Need to Know Timothy Good UFOs military intelligence', NULL, 'need to know,good,military,intelligence', '', 34);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('Intruders', 'Budd Hopkins', 'The New York Times bestseller that mainstreamed the abduction narrative — the Kathie Davis Indiana case, missing time, the hybrid-breeding theme. Dedicated to J. Allen Hynek; spawned the 1992 CBS miniseries.', 'Intruders Budd Hopkins', '0345346335', 'abduction,hopkins,missing time,copley', '', 35);
