-- 0051_affiliate_shelf4.sql: fourth wave of Reading Shelf picks (36 -> 48).
-- Mirrors worker/lib/affiliate.ts PICKS entries 36-47 (sort order).
-- NOTE: 0050 is taken (another session's 0050_post_images.sql); this uses 0051.
-- Apply via the d1-migrate workflow_dispatch; verify with: SELECT count(*) FROM affiliate_picks;  -- expect 48

INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('Faded Giant', 'Robert Salas', 'March 1967, Malmstrom AFB: Salas sat the Oscar Flight capsule while UFOs shut down 10 Minuteman missiles overhead. The firsthand account behind the archive''s nuclear-sites files.', 'Faded Giant Robert Salas', '1419603418', 'malmstrom,missile,oscar flight,salas,1967', 'nuclear-sites', 36);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('The Andreasson Affair', 'Raymond E. Fowler', 'A 12-month CUFOS investigation of Betty Andreasson''s 1967 Massachusetts abduction — hypnosis transcripts, lie-detector tests, her own drawings. The best-documented close encounter of the fourth kind of its era.', 'The Andreasson Affair Raymond Fowler', '1601633467', 'andreasson,betty,abduction,ce-iv,fowler', '', 37);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('Missing Time', 'Budd Hopkins', 'The book that coined ''missing time'' as the common thread of abduction reports — seven experiencers under hypnosis. The clinical foundation Hopkins, Jacobs and Mack all built on.', 'Missing Time Budd Hopkins', '0345353358', 'missing time,hopkins,hypnosis,abduction', '', 38);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('The Threat', 'David M. Jacobs', 'Temple historian Jacobs'' 700+ regression interviews argue a covert hybrid-breeding agenda aimed at domination — the darkest academic reading of the abduction files, and the counterweight to Mack.', 'The Threat David Jacobs', '0684848139', 'jacobs,hybrids,threat,abduction,roper', '', 39);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('Passport to the Cosmos', 'John E. Mack', 'Mack''s follow-up to Abduction — the Harvard psychiatrist''s case that the phenomenon demands a new science of human experience. He survived a Harvard inquiry into his methods.', 'Passport to the Cosmos John Mack', '0609805576', 'mack,cosmos,experiencers,harvard,transformation', '', 40);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('In Plain Sight', 'Ross Coulthart', 'Five-time Walkley winner Coulthart''s investigation of the modern disclosure beat — the Wilson/Davis memos, crash-retrieval claims, Nat Kobitz''s admission. The journalist''s entry point to the UAP era.', 'In Plain Sight Ross Coulthart', 'B09B7ZJ9TP', 'coulthart,disclosure,wilson,crash retrieval,uap', 'congress', 41);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('Encounters', 'D. W. Pasulka', 'Pasulka''s follow-up to American Cosmic — experiencers, the Trinity crash material, AI-as-intelligence, and the UFO-as-religion thesis extended into the disclosure era.', 'Encounters D W Pasulka', '1250879566', 'pasulka,encounters,nonhuman,trinity,experiencers', '', 42);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('Pascagoula', 'Calvin Parker', 'October 1973, Mississippi: Parker''s firsthand account of the abduction that turned skeptical deputies into believers — includes his full hypnotic-regression transcript with the late Budd Hopkins.', 'Pascagoula Calvin Parker', '198299584X', 'pascagoula,hickson,parker,1973,mississippi', '', 43);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('The Invisible College', 'Jacques Vallée', 'Vallée''s ''control system'' hypothesis — UFO encounters as a belief-manipulation mechanism operating across history. Written out of his Project Blue Book years alongside Hynek.', 'The Invisible College Jacques Vallee', '1938398513', 'vallee,invisible college,control system,hynek', '', 44);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('The Aztec UFO Incident', 'Scott & Suzanne Ramsey', 'The Ramseys'' case for the alleged 1948 Aztec, New Mexico saucer recovery — declassified documents, eyewitness interviews, and the Frank Scully story revisited with new evidence. Preface by Stanton Friedman.', 'The Aztec UFO Incident Ramsey', '1632650010', 'aztec,crash,new mexico,1948,scully', '', 45);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('Socorro ''Saucer''', 'Ray Stanford', 'April 1964, Lonnie Zamora''s landing — Stanford''s account, including his claim that NASA-Goddard scientists suppressed metal-fragment test results at the intelligence community''s behest. He arrived at the site alongside Hynek.', 'Socorro Saucer Ray Stanford', '0917092007', 'socorro,zamora,1964,landing,pentagon', '', 46);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('The Braxton County Monster', 'Frank C. Feschino Jr.', 'September 1952, Flatwoods, West Virginia — tied to the Washington DC saucer swarms of July 1952, Project Blue Book, and Ruppelt''s investigation. The deep dive on the Flatwoods Monster.', 'The Braxton County Monster Feschino', '0578128837', 'flatwoods,braxton,1952,monster,west virginia', 'project-blue-book', 47);
