-- 0052_affiliate_audiobooks.sql: Audible audiobook picks (48 -> 58).
-- Mirrors worker/lib/affiliate.ts PICKS entries 48-57 (sort order).
-- Titles carry the 🎧 prefix to distinguish audiobook editions on the shelf.
-- Apply via the d1-migrate workflow_dispatch in small batches (4 rows max per
-- dispatch — large statements fail); verify with: SELECT count(*) FROM affiliate_picks;  -- expect 58

INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('🎧 Dimensions (Audiobook)', 'Jacques Vallée · narrated by Michael Hacker', 'Vallée''s landmark 1988 book arguing the ET hypothesis ''is simply not strange enough'' — centuries of encounters reexamined through an interdimensional lens. A foundation text of serious ufology, in audio.', 'Dimensions Jacques Vallee audiobook', 'B09BK93VZC', 'vallee,dimensions,alien contact,interdimensional', '', 48);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('🎧 Operation Trojan Horse (Audiobook)', 'John A. Keel · narrated by Michael Hacker', 'Keel''s 1970 classic that shredded the nuts-and-bolts ET hypothesis, linking UFOs to paranormal and folkloric phenomena across history. The book that introduced the ''ultraterrestrial'' concept.', 'Operation Trojan Horse John Keel audiobook', 'B07L5YSW96', 'keel,trojan horse,ultraterrestrial', '', 49);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('🎧 The Mothman Prophecies (Audiobook)', 'John A. Keel · narrated by Craig Wasson', 'Keel''s firsthand investigation of the 1966–67 Point Pleasant events — Mothman sightings, UFO flaps, Men in Black, and the Silver Bridge collapse. The best-selling Keel title, basis for the 2002 film.', 'The Mothman Prophecies John Keel audiobook', 'B00006JMD5', 'mothman,point pleasant,keel,1966', '', 50);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('🎧 Walking Among Us (Audiobook)', 'David M. Jacobs · narrated by Jeff Cummings', 'Jacobs'' follow-up to The Threat (on the print shelf): his claim that alien-human hybrids are integrating into everyday society, drawn from 1,150+ abduction events he investigated.', 'Walking Among Us David Jacobs audiobook', 'B013FASEFO', 'jacobs,abduction,hybrids,walking among us', '', 51);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('🎧 Confrontations (Audiobook)', 'Jacques Vallée · narrated by Michael Hacker', 'Vallée personally investigates 40 UFO cases worldwide, focusing on physical trace evidence — ground traces, burns, electromagnetic interference. The empirical core of his Alien Contact trilogy.', 'Confrontations Jacques Vallee audiobook', 'B0BV5YZXXK', 'vallee,confrontations,trace evidence,landing', '', 52);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('🎧 1973 (Audiobook)', 'Philip Mantle with Kevin Randle', 'The pivotal 1973 UFO wave — unprecedented landings, the Pascagoula abduction of Hickson and Parker, and the Coyne helicopter close encounter. Pairs with the shelf''s Pascagoula pick.', '1973 Philip Mantle UFO audiobook', 'B0CJZK49B9', '1973,pascagoula,coyne,wave,ufo wave', '', 53);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('🎧 Forbidden Science 5 (Audiobook)', 'Jacques Vallée', 'Ten years of Vallée''s journals, 2000–2009 — partly drawn from classified research: the reframing of the phenomenon for the 21st century, the road to ''disclosure,'' and how 9/11 set the field back.', 'Forbidden Science 5 Jacques Vallee audiobook', 'B0H6GN4VFB', 'vallee,forbidden science,disclosure', '', 54);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('🎧 Forbidden Science 6 (Audiobook)', 'Jacques Vallée · narrated by Michael Hacker', 'The latest journal volume, 2010–2019 — why the highly classified project Vallée joined could never solve the mystery, plus field investigations across Brazil, Argentina, Europe, and Russia.', 'Forbidden Science 6 Jacques Vallee audiobook', 'B0FGZCT7TV', 'vallee,forbidden science,brazil', '', 55);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('🎧 UFO by Garrett Graff (Audiobook)', 'Garrett M. Graff · narrated by Jacques Roy', 'Pulitzer finalist Graff''s deeply reported history of the government''s decades-long UFO quest, 1947 through AATIP. ''One of the rare books on the topic that manages to be both entertaining and factually grounded.'' — WSJ', 'UFO Garrett Graff audiobook', 'B0BW1ZC4V5', 'graff,aatip,government,1947', '', 56);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('🎧 The Eighth Tower (Audiobook)', 'John A. Keel · narrated by Michael Hacker', 'Keel''s darkest work — asks whether a single intelligent force stands behind UFOs, religious apparitions, ghosts, and occult phenomena alike. The full statement of his ''superspectrum'' theory.', 'The Eighth Tower John Keel audiobook', 'B07MTQRW1C', 'keel,eighth tower,ultraterrestrial,superspectrum', '', 57);
