-- 0053_affiliate_docs.sql: documentary picks (58 -> 64).
-- Mirrors worker/lib/affiliate.ts PICKS entries 58-63 (sort order).
-- Titles carry the 🎬 prefix to distinguish documentaries on the shelf.
-- Only The Program has a verified ASIN; the rest use Amazon search fallback.
-- Apply via the d1-migrate workflow_dispatch in small batches (4 rows max per
-- dispatch — large statements fail); verify with: SELECT count(*) FROM affiliate_picks;  -- expect 64

INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('🎬 The Program (2024)', 'James Fox', 'Fox''s latest — the bipartisan congressional push to uncover what intelligence agencies really know about UAP. Follows The Phenomenon with new witnesses and the D.C. disclosure beat.', 'The Program James Fox documentary', 'B0FSD45GRX', 'the program,congress,uap,disclosure,fox', '', 58);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('🎬 The Phenomenon (2020)', 'James Fox · narrated by Peter Coyote', '70 years of sightings through the Pentagon-videos lens — Kenneth Arnold, Roswell, Ariel School, Westall, Rendlesham, plus Harry Reid saying ''most of it hasn''t seen the light of day.''', 'The Phenomenon James Fox documentary', NULL, 'phenomenon,harry reid,ariel,westall,rendlesham', '', 59);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('🎬 Moment of Contact (2022)', 'James Fox', 'The 1996 Varginha, Brazil incident — UFO crash, strange creatures, military cordon, and a policeman''s mysterious death. Witness-by-witness investigation with Stanton Friedman and Brazilian Air Force officers.', 'Moment of Contact James Fox documentary', NULL, 'varginha,brazil,moment of contact,1996', '', 60);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('🎬 Bob Lazar: Area 51 & Flying Saucers (2018)', 'Jeremy Corbell', 'Lazar''s story in his own words — S-4, element 115, the saucers he claims to have worked on. Mickey Rourke narrates. Watch it, then read the archive''s Area 51 files and decide for yourself.', 'Bob Lazar Area 51 Flying Saucers documentary', NULL, 'lazar,area 51,s-4,groom lake', '', 61);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('🎬 Ariel Phenomenon (2022)', 'Randall Nickerson', 'September 1994, Ruwa, Zimbabwe — 62 schoolchildren describe the same landed craft and beings. John Mack''s interviews anchor this careful revisit of one of the most witnessed close encounters on record.', 'Ariel Phenomenon documentary', NULL, 'ariel,zimbabwe,school,1994,mack', '', 62);
INSERT INTO affiliate_picks (title, creator, blurb, query, asin, match_keywords, topics, sort) VALUES ('🎬 The Nimitz Encounters (2019)', 'Dave Beaty', 'The 2004 Tic Tac incident from the carrier deck — Fravor, Dietrich, and the Princeton crew walk through the encounters that reopened the Pentagon''s UAP investigation.', 'The Nimitz Encounters documentary', NULL, 'nimitz,tic tac,fravor,2004,aawsap', '', 63);
